name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
    - name: Format check
      run: cargo fmt --all -- --check      
    - name: Unit tests
      run: cargo test --lib
    - name: API tests
      run: cargo test --test api
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings